# Generated by Django 4.1.7 on 2023-03-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True, unique_for_date='publish'),
        ),
    ]
